export enum ActionType {
  SCREENSHOT = 'SCREENSHOT',
  EVENT = 'EVENT',
  RECORD_BY_IMAGE = 'RECORD_BY_IMAGE',
  RECORD_BY_LABEL = 'RECORD_BY_LABEL',
  COMMENT = 'COMMENT',
  NAVIGATE = 'NAVIGATE'
}
